
type Municipios = {
    [key: string]: string[] | boolean;
}

export const municipios: Municipios = {
    "BELFORDROXO": ["BASE SAMU", "HMBR", "UPA LOTE XV"],
    "CAXIAS": [
        "BASE SAMU", "CAMPOS ELÍSEOS", "HOSPITAL ADÃO PEREIRA NUNES", "HOSPITAL MOACYR RODRIGUES",
        "UPA INFANTIL WALTER GARCIA", "UPA PARQUE LAFAIETE", "UPA SARAPUI", "UPH IMBARIÊ", "UPH SARACURUNA",
        "XERÉM"
    ],
    "CENTRAL SAMU": false,
    "GOVBR": false,
    "ITAGUAÍ": ["BASE SAMU", "HOSPITAL SÃO FRANSCISCO XAVIER", "UPA DE ITAGUAÍ"],
    "JAPERI": ["BASE SAMU", "HOSPITAL MUNICIPAL DE JAPERI", "POLICLÍNICA ITÁLIA FRANCA"],
    "MAGÉ": [
            "BASE SAMU", "HOSP MAT INF HUGO BRAGA", "HOSPITAL DE MAGÉ", "POSTO 24H MAUÁ", "POSTO 24H MAUÁ",
            "POSTO 24H SANTO ALEIXO", "POSTO 24H SURUPI", "UNIDADE MISTA DE MAUÁ", "UPA MAGÉ"
            ],
    "MESQUITA": ["BASE SAMU", "SES RJ UPA MESQUITA"],
    "NILOPOLIS": ["APONTADORIA", "BASE SAMU"],
    "NOVA IGUAÇU": ["BASE SAMU", "HGNI", "MARIANA BULHÕES", "UPA BOTAFOGO", "UPA CABUÇU", "UPA COMENDADOR SOARES"],
    "PARACAMBI": ["BASE SAMU", "HOSPITAL MUNICIPAL PARACAMBI"],
    "QUEIMADOS": ["BASE SAMU", "CENTRO DE TRIAGEM", "UPA DE QUEIMADOS"],
    "SÃO JOÃO DE MERITI": ["BASE SAMU", "HOSPITAL ABDON GONÇALVES", "UPA JARDIM ÍRIS"],
    "CISBAF": ["RH", "LICITAÇÃO", "CONTABILIDADE", "ALMOXARIFADO", "TI", "COMUNICAÇÃO", "CONTROLE INTERNO", "NEP", "JURIDÍCO", "OUTRO"],
    "SEROPÉDICA": ["BASE SAMU", "UPA SEROPÉDICA", "UPH DR. JOSÉ BUENO LOPES"],
    "UNIDADE MISTA DE SURUÍ": false,
    "UPA JARDM ÍRIS": false
}